//还款状态
const REPAY_STATUS = 'REPAY_STATUS';
//还款方式
const REPAY_WAY = 'REPAY_WAY';
//放款类型
const LOAN_TYPE = 'LOAN_TYPE';
//放款状态
const PAYMENT_STATUS = 'PAYMENT_STATUS';
//财务放款类型
const FINANCIAL_TYPE = 'FINANCIAL_TYPE';
//账户(开户)类型
const ACCOUNT_TYPE = 'ACCOUNT_TYPE';
//开户状态
const OPEN_STATUS = 'OPEN_STATUS';
//交易类型
const FEE_TYPE='FEE_TYPE';

//产品状态(上下架产品)
const PRODUCT_STATUS = 'PRODUCT_STATUS'
//产品策略状态(启用禁用产品策略)
const STRATEGY_STATUS = 'STRATEGY_STATUS' //kind group同PRODUCT_STATUS
//计息方式
const INTEREST_RATE = 'INTEREST_RATE'; //kind group同PRODUCT_STATUS
//还款日
const REPAY_DAY = 'REPAY_DAY'; //kind group同PRODUCT_STATUS
//提前还款违约金计算方式
const DEFAULTS_CAL_METHOD = 'DEFAULTS_CAL_METHOD'; //kind group同PRODUCT_STATUS
//期数
const REPAY_TERMS = 'REPAY_TERMS';
//产品类型
const LOAN_KIND = 'LOAN_KIND'; //kind
const PRODUCT = 'PRODUCT';   //group


//授信申请状态
const CREDIT_STATUS = 'CREDIT_STATUS';
const CREDIT = 'CREDIT';
//担保申请状态
const GUARANTEE_STATUS = 'GUARANTEE_STATUS';
const GUARANTEE = 'GUARANTEE';
//借款申请状态(还款状态)
const LOAN_STATUS = 'LOAN_STATUS';
const LOAN = 'LOAN';
//借款用途
const USAGE_LOAN = 'USAGE_LOAN'; //group  LOAN

//认证类型(身份证/运营商/淘宝)
const AUTH = 'AUTH';
//婚姻状况
const MARITAL = 'MARITAL';
//性别
const SEX = 'SEX';
/*
* 1.全部的关系 kind: RELATIONSHIP  noGroup
* 2.亲属关系  kind: RELATIONSHIP group: RELATIONSHIP
* 3.其他联系人关系  kind: RELATIONSHIP group: CONTACT_RELATIONSHIP
* */
//亲属关系
const RELATIONSHIP = 'RELATIONSHIP'; //group kind同一个
//其他联系人关系
const CONTACT_RELATIONSHIP = 'CONTACT_RELATIONSHIP'; //kind RELATIONSHIP

//亲属关系列表
const RELATIONSHIP_LIST = [
  'PP_FATHER',
  'PP_MOTHER',
  'PP_BROTHER',
  'PP_SISTERS',
  'PP_SPOUSE',
  'PP_CHILDREN'
];
//便宜关系列表
const REL_FRIEND_LIST = [
  'PP_COLLEAGUE',
  'PP_CLASSMATE',
  'PP_FRIEND'
];

//法人年收入
const ANNUAL_SALARY = 'ANNUAL_SALARY'
//企业收益
const ENTERPRISE_INCOME = 'ENTERPRISE_INCOME'
//公司类型
const COMPANY_TYPE = 'COMPANY_TYPE'


//资产信息
const ASSET = 'ASSET'
//资产性质
const ASSET_FEATURES = 'ASSET_FEATURES'; //kind group同ASSET
//资产状态
const ASSET_STATUS = 'ASSET_STATUS'; //kind group同ASSET


const HOUSE_PROPERTY = 'HOUSE_PROPERTY'; //房产
const CAR_PROPERTY = 'CAR_PROPERTY';   //车辆

//电核状态
const MOBILE_EXAMINE = 'MOBILE_EXAMINE';
const FLUENT = 'FLUENT'; //流畅

//授信审核 审核结果
const WORKFLOW = 'WORKFLOW';  //group
const OPERATION = 'OPERATION';  //kind
//还款来源
const PAYMENT = 'PAYMENT';
// 资金账户提现方式
const WITHDRAW_TYPE='WITHDRAW_TYPE';
//  产品还款方式
const REPAYMENT_TYPE='REPAYMENT_TYPE';


//个人材料
const PERSON = 'PERSON';  //group
const PROOF_MATERIAL = 'PROOF_MATERIAL'; //kind

const USER_IDENTITY = 'USER_IDENTITY'; //身份证正面
const USER_IDENTITY_BACK = 'USER_IDENTITY_BACK'; //身份证反面
const HAND_USER_IDENTITY = 'HAND_USER_IDENTITY'; //手持身份证
const SPOUSE_IDENTIT = 'SPOUSE_IDENTIT'; //配偶身份证正面
const SPOUSE_IDENTITY_BACK = 'SPOUSE_IDENTITY_BACK'; //配偶身份证反面
const PERSONAL_RESIDENCE_BOOK = 'PERSONAL_RESIDENCE_BOOK'; //户口本照片
const MARRIAGE_LICENSE = 'MARRIAGE_LICENSE'; //结婚证
const USER_OTHER_MATERIAL = 'USER_OTHER_MATERIAL'; //其他
const BANK_CREDIT_REPORT = 'BANK_CREDIT_REPORT'; //央行征信报告
const SPOUSE_BANK_CREDIT_REPORT = 'SPOUSE_BANK_CREDIT_REPORT'; //配偶央行征信报告
const DOMICILE_BUSINESS_CERTIFICATE = 'DOMICILE_BUSINESS_CERTIFICATE'; //居住地证明信息

const NET_EXAMINE_STATUS = 'NET_EXAMINE_STATUS'; //网核信息

//央行征信报告
const PROP = 'PROP'; //kind PROOF_MATERIAL

//公司材料
const ORG = 'ORG'; //group: PROOF_MATERIAL
const COM_BUSINESS_LICENSE = 'COM_BUSINESS_LICENSE' //营业执照正本
const COM_BUSINESS_LICENSE_DEPUTY = 'COM_BUSINESS_LICENSE_DEPUTY' //营业执照副本
const COM_TAX_REGISTRATION_CERTIFICATE = 'COM_TAX_REGISTRATION_CERTIFICATE' //税务登记证正本
const COM_ACCOUNT_PERMITS = 'COM_ACCOUNT_PERMITS' //开户许可证正本
const COM_CREDIT_CODE_CERTIFICATE = 'COM_CREDIT_CODE_CERTIFICATE' //信用代码证正本
const COM_ORGANIZATION_CODE_CERTIFICATE = 'COM_ORGANIZATION_CODE_CERTIFICATE' //组织机构代码证正本
const COM_COMPANY_SEAL = 'COM_COMPANY_SEAL' //公司公章
const COM_RETURN_RECEIPT = 'COM_RETURN_RECEIPT' //对公账户电子回单

/*
* 贷款信息
* */
const LOAN_INFORMATION = 'LOAN_INFORMATION'; //
//贷款类型
const LOAN_TYPE_CREDIT = 'LOAN_TYPE_CREDIT'; //group:LOAN_INFORMATION
//账户状态
const ACCOUNT_STATE_CREDIT = 'ACCOUNT_STATE_CREDIT'; //group:LOAN_INFORMATION
//存续情况
const CONTINUITY = 'CONTINUITY'; //group:LOAN_INFORMATION

//店铺平台
const ELECTRONIC_PLATFORM = 'ELECTRONIC_PLATFORM';

//信用等级
const CREDIT_GRADE = 'CREDIT_GRADE';

//调账审核状态
const RECONCILE_AUDIT_STATUS = 'RECONCILE_AUDIT_STATUS';
const RECONCILE_ACCOUNT = 'RECONCILE_ACCOUNT';

//调账资金操作状态
const RECONCILE_FUND_STATUS = 'RECONCILE_FUND_STATUS';

//调账输入类型
const RECONCILE_INPUT_TYPE = 'RECONCILE_INPUT_TYPE';


export default {
  REPAY_STATUS,
  REPAY_WAY,
  LOAN_TYPE,
  FINANCIAL_TYPE,
  LOAN_STATUS,
  LOAN,
  CREDIT_STATUS,
  CREDIT,
  ACCOUNT_TYPE,
  OPEN_STATUS,
  PRODUCT_STATUS,
  STRATEGY_STATUS,
  GUARANTEE_STATUS,
  GUARANTEE,
  PAYMENT_STATUS,
  INTEREST_RATE,
  REPAY_DAY,
  DEFAULTS_CAL_METHOD,
  AUTH,
  MARITAL,
  SEX,
  RELATIONSHIP,
  CONTACT_RELATIONSHIP,
  MOBILE_EXAMINE,
  WORKFLOW,
  OPERATION,
  PAYMENT,
  ANNUAL_SALARY,
  USAGE_LOAN,
  WITHDRAW_TYPE,
  REPAYMENT_TYPE,
  FEE_TYPE,
  USER_IDENTITY,
  USER_IDENTITY_BACK,
  HAND_USER_IDENTITY,
  SPOUSE_IDENTIT,
  SPOUSE_IDENTITY_BACK,
  PERSONAL_RESIDENCE_BOOK,
  MARRIAGE_LICENSE,
  PROOF_MATERIAL,
  PERSON,
  USER_OTHER_MATERIAL,
  ASSET_FEATURES,
  ASSET_STATUS,
  ASSET,
  BANK_CREDIT_REPORT,
  SPOUSE_BANK_CREDIT_REPORT,
  PROP,
  LOAN_INFORMATION,
  LOAN_TYPE_CREDIT,
  ACCOUNT_STATE_CREDIT,
  CONTINUITY,
  ENTERPRISE_INCOME,
  COMPANY_TYPE,
  ORG,
  COM_BUSINESS_LICENSE,
  COM_BUSINESS_LICENSE_DEPUTY,
  COM_TAX_REGISTRATION_CERTIFICATE,
  COM_ACCOUNT_PERMITS,
  COM_CREDIT_CODE_CERTIFICATE,
  COM_ORGANIZATION_CODE_CERTIFICATE,
  COM_COMPANY_SEAL,
  COM_RETURN_RECEIPT,
  ELECTRONIC_PLATFORM,
  REPAY_TERMS,
  FLUENT,
  LOAN_KIND,
  PRODUCT,
  CREDIT_GRADE,
  RELATIONSHIP_LIST,
  REL_FRIEND_LIST,
  HOUSE_PROPERTY,
  CAR_PROPERTY,
  DOMICILE_BUSINESS_CERTIFICATE,
  NET_EXAMINE_STATUS,
  RECONCILE_AUDIT_STATUS,
  RECONCILE_FUND_STATUS,
  RECONCILE_INPUT_TYPE,
  RECONCILE_ACCOUNT
}
